name: CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 985539772768.dkr.ecr.us-east-1.amazonaws.com
      - name: Create ECR Repositories
        run: |
          for repo in lab6-ecommerce-validation lab6-ecommerce-staging lab6-ecommerce-transformation lab6-ecommerce-dynamodb; do
            aws ecr describe-repositories --repository-names $repo || aws ecr create-repository --repository-name $repo
          done
      - name: Build and Push Docker Images
        run: |
          for dir in validation staging kpi_computation dynamodb_write; do
            cd $dir
            docker build -t 985539772768.dkr.ecr.us-east-1.amazonaws.com/lab6-ecommerce-$dir:latest .
            docker push 985539772768.dkr.ecr.us-east-1.amazonaws.com/lab6-ecommerce-$dir:latest
            cd ..
          done
      - name: Register Task Definitions
        run: |
          for dir in validation staging kpi_computation dynamodb_write; do
            aws ecs register-task-definition --cli-input-json file://$dir/task-definition.json
          done
